"""phone-number

Revision ID: 6cbdae324a73
Revises: 0bceca381485
Create Date: 2022-11-14 21:36:20.705555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# alembic revision autogenerate -m "phone-number"

# revision identifiers, used by Alembic.
revision = '6cbdae324a73'
down_revision = '0bceca381485'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('posts')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###
# alembic upgrade head / code / +1


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # op.create_table('posts',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    # sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='posts_pkey')
    # )
    # ### end Alembic commands ###
# alembic upgrade head / code / +1
